CREATE TABLE classes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_classes PRIMARY KEY (id)
);

CREATE TABLE grades
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grade       numeric(2, 1)                           NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    student_id  BIGINT                                  NOT NULL,
    test_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_grades PRIMARY KEY (id)
);

CREATE TABLE knowledge_tests
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    category   VARCHAR(255)                            NOT NULL,
    test_date  date                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    class_id   BIGINT                                  NOT NULL,
    subject_id BIGINT                                  NOT NULL,
    teacher_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_knowledge_tests PRIMARY KEY (id)
);

CREATE TABLE students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    firstname  VARCHAR(255)                            NOT NULL,
    lastname   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    class_id   BIGINT,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE subjects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

CREATE TABLE teachers_subjects
(
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    firstname  VARCHAR(255)                            NOT NULL,
    lastname   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    class_id   BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE classes
    ADD CONSTRAINT uc_classes_name UNIQUE (name);

ALTER TABLE knowledge_tests
    ADD CONSTRAINT uc_knowledge_tests_name UNIQUE (name);

ALTER TABLE students
    ADD CONSTRAINT uc_students_email UNIQUE (email);

ALTER TABLE subjects
    ADD CONSTRAINT uc_subjects_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_class UNIQUE (class_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_TEST FOREIGN KEY (test_id) REFERENCES knowledge_tests (id);

ALTER TABLE knowledge_tests
    ADD CONSTRAINT FK_KNOWLEDGE_TESTS_ON_CLASS FOREIGN KEY (class_id) REFERENCES classes (id);

ALTER TABLE knowledge_tests
    ADD CONSTRAINT FK_KNOWLEDGE_TESTS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE knowledge_tests
    ADD CONSTRAINT FK_KNOWLEDGE_TESTS_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES users (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_CLASS FOREIGN KEY (class_id) REFERENCES classes (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_CLASS FOREIGN KEY (class_id) REFERENCES classes (id);

ALTER TABLE teachers_subjects
    ADD CONSTRAINT fk_teasub_on_subject FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE teachers_subjects
    ADD CONSTRAINT fk_teasub_on_user FOREIGN KEY (teacher_id) REFERENCES users (id);

INSERT INTO users(email, password, firstname, lastname, role, created_at, updated_at, class_id)
VALUES ('admin@gmail.com', '$2a$12$dZ7W.3Xyk.Y2TyoSMioupezNJgSEqACVo8pIF.6ns5JfSF0CgN4ki', 'admin', 'admin', 'ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);